### ISSUE TITLE
Article on randomness in applications; review needed

### ISSUE THREAD

**Issue by peteroupc** [peteroupc/peteroupc.github.io#1]
I have published an article on [randomness in applications](http://peteroupc.github.io/random.html) on peteroupc.github.io.  This is actually not a new article, but rather copied from [CodeProject](http://www.codeproject.com/Tips/1083372/The-Two-Kinds-of-Random-number-Generators-Most-App), where it has been for some time, although I also edited it there recently.

I encourage anyone to review and comment on this article, but I would especially like @lcrocker to see this article. (I know Lee Crocker is very familiar with random number generation; I tried to email him, but the message was undeliverable.) Comments on any aspect of the document are welcome, but answers to the following would be particularly appreciated.

1. Are there non-trivial applications that can be described as follows?

    - The application uses random numbers for non-security purposes.
    - The application does not require repeatable random numbers.
    - The application generates random numbers so frequently that using a cryptographic RNG would be too slow.

2. Are there important classes of applications that require repeatable random numbers, besides the ones I list in "[Manually Seeded PRNG Use Cases](https://peteroupc.github.io/random.html#Manually_Seeded_PRNG_Use_Cases)"?

3. What implementations of [**high-quality PRNGs**](https://peteroupc.github.io/random.html#High_Quality_PRNG_Examples) exist for various programming languages?  They should allow users to seed their full state (not just 32 or 64 bits of it), and should not use global variables.   They should also be trivial to include in other programs.   See also [my current list](https://peteroupc.github.io/random.html#Existing_RNG_APIs_in_Programming_Languages).

**Comment by peteroupc** [comment]
I would also like comments on the following questions:

In a typical computer a consumer would have today:
- How many random numbers per second would a cryptographic RNG generate?  A high-quality noncryptographic RNG?
- How many random numbers per second does a typical application using RNGs generate?  Are there applications that usually generate considerably more random numbers than that per second?

**Comment by lcrocker** [comment]
I'll take a look thanks, and I also at my email. I think one of my addresses is bouncing because of a full mailbox.

**Comment by peteroupc** [comment]
@lcrocker: Have you finished your review of this article?

**Comment by lcrocker** [comment]
Pretty reasonable. I think some readers might be confused between a PRNG's seed and its full internal state (whose size you call "seed length" in the article). I think you also understate the usefulness of raw speed in applications like simulation and Monte Carlo integration.  For example, you suggest using a cryptographic RNG for shuffling cards on the assumption that most PRNGs have an internal state that is too small. But it is far better to use a fast PRNG with a big state. When I worked for a casino, my employer wanted to know how often a certain jackpot would hit. I had to simulate *billions* of hands of poker or blackjack. There's no way I could have done that with a slow secure RNG. 

I think it's also important to give users the most important advice of all: Don't roll your own. The RNGs that come with most modern programming languages are actually pretty decent these days, and those that aren't typically have add-on libraries that are better.

Finally, I don't think you emphasize enough that things like /dev/random and CryptGenRandom get much of their value by using physical hardware means to create entropy: things like reverse-biased diode timings and such.

**Comment by peteroupc** [comment]
I have updated the document in response to your review.  In addition, I have added a new question to the request for comments (in the document): "Are there existing programming language APIs or software libraries, not mentioned in this document, that already meet the requirements for unpredictable-random or statistical-random RNGs?".

I encourage further review, either by you or anyone else, on the new version of the document.

(I post again directly in case the email reply fell through.)

**Comment by peteroupc** [comment]
I have edited this document several times since June 14.  I encourage further review, either by @lcrocker or anyone else, on the new version of the document.

**Comment by peteroupc** [comment]
I have made many updates to my [random number article](https://github.com/peteroupc/peteroupc.github.io/blob/master/random.md) since last August.  I now encourage further review by anyone.

@lcrocker, @d3e3e3, can you please review this?

**Comment by peteroupc** [comment]
Suggesting to @dj-on-github to review this article of mine.  I wasn't aware until today that he published a book on RNGs, so he seems an excellent reviewer.

**Comment by dj-on-github** [comment]
I'll check it out and make some comments.

**Comment by dj-on-github** [comment]
I have concerns about the JitterRand paper you reference. On page 34 it
claims the Chi-Sq test frequently returns a 50.00% "perfect" result. The P
value from the Chi-Sq test when fed nondeterministic uniform random data is
itself uniformly distributed between 0% and 100%. So a 50.00% result only
happens once every 10,000 runs. 50.00% is as likely as every other
percentage represented down to 2 decimal places. 50.00% is not a 'perfect'
result. It is no better than any other result. So a paper where someone
claims to get that result because it's perfect is suspect. It then shows
two runs of ent on the same file returning 25.00%.

If I do this myself against the RdRand output that is an SP800-90A DRBG
output that is certified, crypto secure and statistically indistinguishable
from random, I get results like this:
# quickrdrand -b -k 78125 > random.out
# djent -b -l 8 -e random.out
Min Entropy (by max occurrence of symbol 1f) = 0.999039
Entropy = 7.999997 bits per byte.

Optimum compression would reduce the size
of this 80000000 byte file by 0 percent

Chi square distribution for 80000000 samples is 292.974387, and randomly
would exceed this value less than 5.114881 percent of the times.

Arithmetic mean value of data bytes is 127.487290 (127.5 = random).
Monte Carlo value for Pi is 3.142500 (error 0.028875 percent).
Serial correlation coefficient is -0.000849 (totally uncorrelated = 0.0).

Repeating this a few times, the chi-sq percentage varies as expected. This
is covered in my book.

DJ

**Comment by peteroupc** [comment]
Thank you for that.

I assume you are still working on your review?  If not, then I would have expected that you would tell me how each part of my article can be improved, that is, whether there are issues with any of my suggestions in that article.  For example, I made several suggestions for cryptographic and noncryptographic RNGs and how they should be implemented and used, and gave examples of each.  Are those suggestions reasonable?  Do you have other comments on my article?

Note that I cited the Jitter RNG because it was another example of a nondeterministic source, not necessarily because of what it says about chi-square tests.  Note that testing RNGs is outside the scope of my article.

**Comment by dj-on-github** [comment]
Yes. I’m still absorbing it. One comment is you don’t mention on chip
sources like RdRand, RdSeed and Xstore instructions, when these are the
primary sources of entropy deployed today.

I have bigger concerns with Jitterrandom and the made-up test results are
just a clue.

I’ll have more comments on the substance of the article in a bit.

DJ

**Comment by peteroupc** [comment]
@dj-on-github : Have you finished working on your comments for this article?

**Comment by dj-on-github** [comment]
No. I’ve been occupied at work.

**Comment by peteroupc** [comment]
@dj-on-github : I have now revised this article quite a bit.

**Comment by peteroupc** [comment]
I have now revised [this article](https://github.com/peteroupc/peteroupc.github.io/blob/master/random.md) quite a bit.  The article now speaks of "manually-seeded PRNGs" and "high-quality PRNGs" rather than "seeded" and "statistical" RNGs, respectively.  The article also includes its own top-level section on _verifiable random numbers_. I have also edited the opening post of this issue and replaced its questions with the following, which could help me improve my article.

1. Are there non-trivial applications that can be described as follows?

    - The application uses random numbers for non-security purposes.
    - The application does not require repeatable random numbers.
    - The application generates random numbers so frequently that using a cryptographic RNG would be too slow.

2. Are there important classes of applications that require repeatable random numbers, besides the ones I list in "[Manually Seeded PRNG Use Cases](https://peteroupc.github.io/random.html#Manually_Seeded_PRNG_Use_Cases)"?

3. What implementations of [**high-quality PRNGs**](https://peteroupc.github.io/random.html#High_Quality_PRNG_Examples) exist for various programming languages?  They should allow users to seed their full state (not just 32 or 64 bits of it), and should not use global variables.  They should also be trivial to include in other programs.  See also [my current list](https://peteroupc.github.io/random.html#Existing_RNG_APIs_in_Programming_Languages).

@dj-on-github : Please consider posting a review of this article now.

**Comment by peteroupc** [comment]
Moved to #6.
