### ISSUE TITLE
Tag definitions available for an Internet-Draft?

### ISSUE THREAD

**Issue by cabo** [peteroupc/peteroupc.github.io#10]
Hi Peter,

I would like to include the tag definitions in this repo (rational, extended, bigfrac) in

https://cabo.github.io/notable-tags/draft-bormann-cbor-notable-tags.html#name-advanced-arithmetic

(and probably some more in other places).  To do this, I'd need your consent, as well as the usual address information for https://cabo.github.io/notable-tags/draft-bormann-cbor-notable-tags.html#name-contributors

Interested in contributing these definitions?

Grüße, Carsten

**Comment by peteroupc** [comment]
Yes. Use the email address contained in the tag definitions.

**Comment by cabo** [comment]
Thanks.  Sorry for being glacial in developing this further, but it's on my list.  -02 of notable-tags already has a brief description for your tag 257.  While adding you to the contributor section, I noticed that the email address in your definitions is (slightly) obfuscated.  This is unusual in RFCs (which this document is intended to become eventually), but I didn't feel I should remove the obfuscation without asking you.

**Comment by peteroupc** [comment]
Closing.
